controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /accueil
    controller: App\Controller\HomeController::accueil

register:
    path: /
    controller: App\Controller\RegistrationController::register
